version: '3'
services:
    api-users-todos:
        build: 
            context: ./src
            target: ${DOCKER_TARGET}
        ports: 
            - ${API_PORT}:${API_PORT}
        container_name: api-users-todos
        depends_on:
            - api-users-todos-db
        networks: 
            - todos-infrastructure
        volumes:
            - ./src:/go/src/app
        command: reflex -r "\.go$$" -s -- sh -c "go run ./"
        env_file: 
            - ./.env

    api-users-todos-db:
        image: postgres
        container_name: api-users-todos-db
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DATABASE=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks: 
            - todos-infrastructure
        volumes: 
            - ./db-data:/var/lib/postgresql/data
networks:
    todos-infrastructure: 
        external: true