version: '3'
services:
    users-service:
        build: 
            context: ./src
            target: ${DOCKER_TARGET}
        ports: 
            - ${APP_PORT}:${APP_PORT}
        container_name: users-service
        depends_on:
            - users-service-db
        networks: 
            - todos-infrastructure
        volumes:
            - ./src:/go/src/app
        command: reflex -r "\.go$$" -s -- sh -c "go run ./"
        env_file: 
            - ./.env

    users-service-db:
        image: postgres
        container_name: users-service-db
        ports:
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DATABASE=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks: 
            - todos-infrastructure
        volumes: 
            - ./db-data:/var/lib/postgresql/data
networks:
    todos-infrastructure: 
        external: true