// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/plagioriginal/user-microservice/domain"
	mock "github.com/stretchr/testify/mock"
)

// RoleService is an autogenerated mock type for the RoleService type
type RoleService struct {
	mock.Mock
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *RoleService) GetBySlug(ctx context.Context, slug string) (domain.Role, error) {
	ret := _m.Called(ctx, slug)

	var r0 domain.Role
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Role); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(domain.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, role
func (_m *RoleService) Store(ctx context.Context, role domain.Role) (domain.Role, error) {
	ret := _m.Called(ctx, role)

	var r0 domain.Role
	if rf, ok := ret.Get(0).(func(context.Context, domain.Role) domain.Role); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(domain.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Role) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
