// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/plagioriginal/user-microservice/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUserByLogin provides a mock function with given fields: ctx, username, password
func (_m *UserService) GetUserByLogin(ctx context.Context, username string, password string) (*domain.User, error) {
	ret := _m.Called(ctx, username, password)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUUID provides a mock function with given fields: ctx, _a1
func (_m *UserService) GetUserByUUID(ctx context.Context, _a1 uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, username, password, roleSlug
func (_m *UserService) Store(ctx context.Context, username string, password string, roleSlug string) (*domain.User, error) {
	ret := _m.Called(ctx, username, password, roleSlug)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = rf(ctx, username, password, roleSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, username, password, roleSlug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
